config/routes.rb
Rails.application.routes.draw do
  resources :empresas
  devise_for :usuarios
  root 'home#index'
  
  post "/" => 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	belongs_to :usuario
	validates :simbolo, presence: true
	validates :simbolo, format: {without: /\s/}  
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :empresas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: %i[ show edit update destroy ]
  before_action :usuario_correcto, only: %i[ edit update destroy ]
  before_action :authenticate_usuario!

  # GET /empresas or /empresas.json
  def index
    @empresas = Empresa.all
  end

  # GET /empresas/1 or /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas or /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to empresa_url(@empresa), notice: "Empresa was successfully created." }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1 or /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to empresa_url(@empresa), notice: "Empresa was successfully updated." }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1 or /empresas/1.json
  def destroy
    @empresa.destroy

    respond_to do |format|
      format.html { redirect_to empresas_url, notice: "Empresa was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def usuario_correcto
    @simbolo = current_usuario.empresas.find_by(id: params[:id])
    redirect_to empresas_path, notice: "No está autorizado a editar esta empresa" if @simbolo.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def empresa_params
      params.require(:empresa).permit(:simbolo, :usuario_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     @api = StockQuote::Stock.new(api_key: 'pk_9a3fffc17adf4052ac921fb0e57968bc')

    if params[:simbolo] == ""
      @nada = "Ehh! Has olvidado entrar la búsqueda"
    elsif params[:simbolo]
      begin
        @bolsa = StockQuote::Stock.quote( params[:simbolo] )
        @logo = StockQuote::Stock.logo( params[:simbolo] )
        @compania = StockQuote::Stock.company( params[:simbolo] ) 
        @noticias = StockQuote::Stock.news( params[:simbolo] )
        
      rescue => e
        @bolsa = nil
        @logo = nil
        @compania = nil
      end
      if @bolsa == nil
          @error = "Ehh! Ese símbolo no existe" 
      end
    end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/empresas/_form.html.erb
<%= form_with(model: empresa) do |form| %>
  <% if empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
        <% empresa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
      <%= form.text_field :simbolo, class:"form-control", placeholder: "Símbolo" %>
  </div>


  <div class="mb-3">
    <% form.label :usuario_id %>
    <%= form.number_field :usuario_id, value: current_usuario.id, type: :hidden %>
    
  </div>

  <div class="mb-3">
    <button type="submit" class="btn btn-primary">Crear Empresa</button>
     
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing Empresa</h1>

<%= render 'form', empresa: @empresa %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<h1>Bolsa de valores</h1>
<div class="table-responsive">
<table class="table table-striped table-hove table-bordered table align-middle">
  <thead class="table-dark">
    <tr>
      <th  scope="col">Empresa</th>
      <th  scope="col">Símbolo</th>
      <th  scope="col">Precio Actual</th>
      
    </tr>
  </thead>

  <tbody>
    <% @empresas.each do |empresa| %>
      <% if empresa.usuario_id == current_usuario.id %>

      <% if empresa.simbolo == "" %>
        <% @nada = "Ehh! Has olvidado entrar la búsqueda" %>
      <% elsif empresa.simbolo %>
        <% begin %>
          <% @bolsa = StockQuote::Stock.quote( empresa.simbolo ) %>
        <% rescue => e %>
          <% @bolsa = nil %>
      <% end %>
        <% if @bolsa == nil %>
          <% @error = "Ehh! Ese símbolo no existe" %>
        <% end %>
    <% end %>
    



     <% if @bolsa %>
        <tr>
          <th scope="row"><%= link_to @bolsa.company_name, empresa %></th>
          <td><%= @bolsa.symbol %></td>
          <td>$<%= number_with_precision(@bolsa.latest_price, :precision => 2, :delimiter => "." ) %></td>
          
          
          
        </tr>
      <% else %>
        <tr>
            <td scope="row"><%= link_to empresa.simbolo, empresa %></td>
            <td> N/A </td>
            <td> N/A </td>
            
            
          </tr>
      <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'Nueva Empresa', new_empresa_path,class:"btn btn-outline-primary" %>

app/views/empresas/new.html.erb
<div class="card text-center" style="max-width: 540px">
  
  <div class="card-body">
    <h3 class="card-title">Nueva Empresa</h3>
    <%= render 'form', empresa: @empresa %>  
  </div>
  <div class="card-body text-end">
  	<%= link_to 'Atrás', empresas_path, class:"card-link" %>
  </div>
</div>

app/views/empresas/show.html.erb
  <% if @empresa.simbolo == "" %>
      <% @nada = "Ehh! Has olvidado entrar la búsqueda" %>
  <% elsif @empresa.simbolo %>
      <% begin %>
          <% @bolsa = StockQuote::Stock.quote( @empresa.simbolo ) %>
          <% @logo = StockQuote::Stock.logo( @empresa.simbolo ) %>
          <% @compania = StockQuote::Stock.company( @empresa.simbolo ) %>
      <% rescue => e %>
          <% @bolsa = nil %>
          <% @logo = nil %>
          <% @compania = nil %>
      <% end %>
        <% if @bolsa == nil %>
          <% @error = "Ehh! Ese símbolo no existe" %>
        <% end %>
  <% end %>
    



     <% if @bolsa %>

        <div class="card mb-3" style="max-width: 540px;">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="<%= @logo.url %>" class="img-fluid rounded-start" alt="logo de la empresa">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><%= @bolsa.company_name %></h5>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">Símbolo: <%= @bolsa.symbol %></li>
                  <li class="list-group-item">Sector: <%= @compania.sector %> </li>
                  <li class="list-group-item">Capital: <%= number_with_precision(@bolsa.market_cap, :precision => 2, :delimiter => "." ) %> <%= @bolsa.currency %></li>
                  <li class="list-group-item">CEO: <%= @compania.ceo %> </li>
                  <li class="list-group-item">Valor actual:<strong> $<%= number_with_precision(@bolsa.latest_price, :precision => 2, :delimiter => "." ) %></strong> </li>
                  <li class="list-group-item">Anterior cierre: $<%= number_with_precision(@bolsa.previous_close, :precision => 2, :delimiter => "." ) %> </li>
                </ul>
              </div>
            </div>
            </div>
            <div class="card-body">
                <p class="card-text"><small class="text-muted"><%= @compania.description %></small></p>
            </div>
            <div class="card-body text-end">
              <%= link_to 'Atrás', empresas_path, class:"card-link" %>
              <%= link_to 'Editar', edit_empresa_path(@empresa), class:"card-link" %>
              <%= link_to 'Eliminar', @empresa, method: :delete, data: { confirm: 'Estás seguro?' }, class:"card-link" %>
            </div>
          </div>
        </div>
    
      <% else %>

      <div class="card text-center">
        <div class="card-header">
          ERROR
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= @empresa.simbolo %></h5>
          <p class="card-text">El símbolo no existe o no tenemos información sobre el mismo.</p>
          <%= link_to 'Eliminar', @empresa, method: :delete, data: { confirm: 'Estás seguro?' }, class:"btn btn-primary"%>
          
        </div>
        <div class="card-footer text-muted">
          Elimínelo, por favor
        </div>
      </div>
         
        
      <% end %>



 |

app/views/home/_mensajes.html.erb
<br/>
<% flash.each do |name, msg| %>


<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= content_tag(:div, msg) %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
      
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Bolsa de Valores', root_path, class:"navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if usuario_signed_in? %>
          <li class="nav-item">
               <%= link_to 'Empresas',  empresas_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
               <%= link_to 'Agregar Empresa',  new_empresa_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
               <%= link_to 'Cuenta',  edit_usuario_registration_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
             <%= link_to 'Salir', destroy_usuario_session_path, method: :delete, data: { confirm: "¿Estás seguro?" },class:"nav-link"  %>
          </li>

        <% else %>
          <li class="nav-item">
             <%= link_to 'Registrarse', new_usuario_registration_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
           <%= link_to 'Entrar', new_usuario_session_path, class:"nav-link"  %>
          </li>

        <% end %>
          
      </ul>
      <%= form_tag root_path, class:"d-flex", method: 'POST' do  %>
        <%= text_field_tag 'simbolo', nil, placeholder: "Entre símbolo/ticker", size: 30, class:"form-control me-2" %>
        <%= submit_tag 'Buscar', class:"btn btn-outline-success" %>
      <% end %>
      


    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Bolsa de valores</h1>
<div class="row">
	<div class="col-sm-6">

	<%= form_tag root_path, method: 'POST' do  %>
		<%= text_field_tag 'simbolo', nil, placeholder: "Entre símbolo/ticker", size: 30 %>
		<%= submit_tag 'Buscar' %>
	<% end %>
 	</div>
	<div class="col-sm-6">
<% if @bolsa %>


	<div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
              <img src="<%= @logo.url %>" class="img-fluid rounded-start" alt="logo de la empresa">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><%= @bolsa.company_name %></h5>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">Símbolo: <%= @bolsa.symbol %></li>
                  <li class="list-group-item">Sector: <%= @compania.sector %> </li>
                  <li class="list-group-item">Capital: <%= number_with_precision(@bolsa.market_cap, :precision => 2, :delimiter => "." ) %> <%= @bolsa.currency %></li>
                  <li class="list-group-item">CEO: <%= @compania.ceo %> </li>
                  <li class="list-group-item">Valor actual:<strong> $<%= number_with_precision(@bolsa.latest_price, :precision => 2, :delimiter => "." ) %></strong> </li>
                  <li class="list-group-item">Anterior cierre: $<%= number_with_precision(@bolsa.previous_close, :precision => 2, :delimiter => "." ) %> </li>
                </ul>
              </div>
            </div>
        </div>
     </div>
     </div>
</div>
<br/><br/>
<div class="container">
	<div class="row">
	<% @noticias.news.each do |noticia| %>
		<div class="col-sm">
		<div class="card" style="width: 18rem;">
		  <img src="<%= noticia['image'] %>" class="card-img-top" alt="<%= noticia["source"] %>">
		  <div class="card-body">
		    <h5 class="card-title"><%= noticia["source"] %></h5>
		    <p class="card-text"><%= noticia["headline"] %></p>
		    <a href="<%= noticia["url"] %>" class="btn btn-primary">Read...</a>
		  </div>
		</div>
		<br/>
		</div>	
	<% end %>
	</div>
</div>

	
<% end %>
<% if @nada %>
	<%= @nada %>
<% end %>
<% if @error %>
	<%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bolsa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <%= render 'home/mensajes' %>
      <br/>
      <%= yield %>
    </div>
  </body>
</html>